<?php 
$this->title = "Editor";
$this->headTitle($this->title);
?>



            <header class="clearfix vertical-padding">

                <h1 class="logo xlarge-push-left large-push-left">
                    Asego Daily<small><?php echo $this->escape($this->title); ?></small>
                </h1>

                <nav class="ink-navigation xlarge-push-right large-push-right half-top-space">
                    <ul class="menu horizontal black">
                        <li class="active"><?php echo $this->loginchecker(); ?></li>
                        <li><?php echo $this->loggedInAs(); ?></li>
                        <li><a href="<?php 
						echo $this->url(array('controller'=>'editor',
'action'=>'add'));?>">Write/Edit</a></li>
                        <li><a href="<?php 
						echo $this->url(array('controller'=>'editor',
'action'=>'index'));?>">View All</a></li>
                    </ul>
                </nav>

            </header>


<br>
<br>
<br>

<section class="column-group gutters">
                <?php
foreach($this->all as $all):
?>
                <div class="all-20 small-100 tiny-100">
                    <h3><a href="<?php echo $this ->url( array('controller' => 'index', 'action' =>'index', 'id'=> $all->id)); ?>"> <?php
echo $this ->escape( $all ->title);
?></a></h3>
                    <?php echo '<img src="' . $this->baseUrl() .'/'.  $this ->escape( $all ->image) .'" alt="">'?>
                    <p>"<?php
echo $this ->summary ( $this->escape( $all ->content), 30);
?>"</p>
                </div>
     <?php endforeach;?>            
            </section>