<?php
$this->title = "Add New User";
$this->headTitle($this->title);

?>
<div id="view-content">
<header class="clearfix vertical-padding">

                <h1 class="logo align-center" style="margin-bottom:-40px">
                    Asego Daily<small><?php echo $this->escape($this->title); ?></small>
                </h1>
                <nav class="ink-navigation xlarge-push-right large-push-right ">
                    <ul class="menu horizontal black">
                        <li class="active"><a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'index'));?>">home</a></li>
<li class="active"><a href="<?php echo $this->url(array('controller'=>'admin',
'action'=>'index'));?>">Admin Panel</a></li>
<li><?php echo $this->loggedInAs(); ?></li>
</header>
<br>
<br>
<?php
echo $this->form ;?>
<br>
<br>
<br>
<br>