<?php
$this->title = "System Users";
$this->headTitle($this->title);
?>
<br /><br />
<?php 
$this->title = "System Users";
$this->headTitle($this->title);
?>
<div id="view-content">
<header class="clearfix vertical-padding">

                <h1 class="logo align-center" style="margin-bottom:-40px">
                    Asego Daily<small><?php echo $this->escape($this->title); ?></small>
                </h1>
                <nav class="ink-navigation xlarge-push-right large-push-right ">
                    <ul class="menu horizontal black">
                        <li class="active"><a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'index'));?>">home</a></li>
<li class="active"><a href="<?php echo $this->url(array('controller'=>'admin',
'action'=>'index'));?>">Admin Panel</a></li>
<li><?php echo $this->loggedInAs(); ?></li>
</header>
<div id="usertable" style= "margin:0 auto; width:50%">
<table id ="newspaper-a" class="all-100" ><tr><th>Email</th>
<th>Role</th>
<th>&nbsp;</th>
</tr>
<?php
foreach($this->user as $user):
?>
<tr>
<td>
<?php
echo $this ->escape( $user ->email);
?>
</td>
<td>
<?php
echo $this ->escape($user->role);
?>
</td>

<td>
<a href ="<?php echo $this ->url( array('controller' => 'admin', 'action' =>'edit', 'id'=> $user->id)); ?> " >Edit</a>
<a href ="<?php echo $this ->url(array ('controller' =>'admin','action'=>'delete','id'=>$user->id));?>">
Delete
</a>
</td>
</tr>
<?php endforeach;?>
</table>
<div class="all-50" style="margin-bottom:100px">
<a style="margin:5px" class="ink-button blue all-100" href ="<?php echo $this ->url(array('controller' => 'admin','action'=>'add'));?>"> Add new User </a>
</div>
</div>
</div>